### PR TITLE
menu: fix highlights for range entries

### LINKED ISSUE #1023: OLED inversion region in Default Swing menu when range is used is offset
The inversion region appears to be at the y level of the separator which means it's a few pixels too high to actually highlight the number correctly.

### PR DESCRIPTION
**Pull request by sapphire-arches**
Fixes #1023

### CODE REVIEW

File: src/deluge/gui/menu_item/range.cpp [hunk 1]
```diff
@@ -195,7 +195,8 @@ void Range::drawPixelsForOled() {
 		hilightStartX = stringStartX;
 		hilightWidth = digitWidth * leftLength;
 doHilightJustOneEdge:
-		deluge::hid::display::OLED::invertArea(hilightStartX, hilightWidth, baseY - 1, baseY + digitHeight + 1,
+		baseY += 4;
```
Comment (m-m-adams) [inline src/deluge/gui/menu_item/range.cpp:198]: nit: it's not clear to me why this is happening so it probably needs a comment

**Review by m-m-adams — APPROVED** [review]
