### PR TITLE
Fix #741 and #743 - Horizontal encoder button in Grid mode

### LINKED ISSUE #741: Solo function not present in grid mode
### Please describe the problem:

Solo is not working on grid mode. Works on rows.

### What is the expected behavior?

For grid to be able to use solo function as it works in rows

### Is there a relevant Pull request?

_No response_

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Built from community

### What is the firmware name:

1.0.0 betaD5331ED

### If possible provide the steps to reproduce the issue and upload additional media:

Hold leftright knob down press the clip on grid mode. It does not solo. It works this way in rows view where you press the mute launch pad.

### PR DESCRIPTION
**Pull request by PaulFreund**

### CODE REVIEW

File: src/deluge/gui/views/session_view.cpp [hunk 1]
```diff
@@ -3525,15 +3548,18 @@ ActionResult SessionView::gridHandlePadsLaunchWithSelection(int32_t x, int32_t y
 
 void SessionView::gridHandlePadsLaunchToggleArming(Clip* clip, bool immediate) {
 	if (immediate) {
-		if (currentUIMode == UI_MODE_HOLDING_HORIZONTAL_ENCODER_BUTTON) {
+		if (horizontalEncoderPressed) {
```
Comment (bobtwinkles) [inline src/deluge/gui/views/session_view.cpp:3551]: shouldn't this be `isUIModeActive(UI_MODE_HOLDING_HORIZONTAL_ENCODER_BUTTON)`, rather than recreating that tracking with `horiznotalEncoderPressed`?

Comment (PaulFreund) [reply src/deluge/gui/views/session_view.cpp:3551]: Normally yes, that's how it was before but it got overwritten by clip being held state. Unfortunately there are a lot of places where ui state is written exclusively and sometimes the behavior relies on previous state to be overwritten and sometimes on an added state in some paths and overwritten in others, etc. The whole session view needs to be overhauled to be consistent again and to make future changes easier.

I hope this little hack to not break anything before Release is justified :D.

Comment (bobtwinkles) [reply src/deluge/gui/views/session_view.cpp:3551]:
```
$ rg 'currentUIMode = ' | wc -l
112
```
yeah that's probably too much to deal with for now

**Review by m-m-adams — APPROVED** [review]
