### PR TITLE
session: do not show info names on 7seg

### LINKED ISSUE #1062: 7SEG lights flicker oddly when pressing certain buttons
### Please describe the problem:

7SEG only
Pressing certain pads (generally ones that don't emit text on the display) seems to illuminate random segments on the display.

### What is the expected behavior?

Random segments shouldn't flicker when pressing certain pads.

### Is there a relevant Pull request?

_No response_

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Nightly, other

### What is the firmware name:

1.0.1, 1.1.0 - 1AD7933 (1/24)

### If possible provide the steps to reproduce the issue and upload additional media:

In this case, SONG (Rows View), press audition pad repeatedly
or
SONG (Grid View), press audition pads repeatedly (any pad on the column where green and blue mode are)
https://github.com/SynthstromAudible/DelugeFirmware/assets/136033640/d921480a-d7db-4b34-957b-f2fd03b8af76

### PR DESCRIPTION
**Pull request by sapphire-arches**
Maybe fixes #1062

### CODE REVIEW

File: src/deluge/gui/views/session_view.cpp [hunk 1]
```diff
@@ -1827,10 +1827,6 @@ void SessionView::renderOLED(uint8_t image[][OLED_MAIN_WIDTH_PIXELS]) {
 
 void SessionView::redrawNumericDisplay() {
 	UI* currentUI = getCurrentUI();
```
Comment (seangoodvibes) [inline src/deluge/gui/views/session_view.cpp:1829]: I think this becomes stale now and no longer required unless you want to use currentUI down below in the function in place of the other getCurrentUI() calls (I would do that).

Comment (sapphire-arches) [reply src/deluge/gui/views/session_view.cpp]: Fixed, thanks!

**Review by seangoodvibes — APPROVED** [review]
