### PR TITLE
Maybe fix compressor gain staging

### LINKED ISSUE #1605: Master volume too loud
### Please describe the problem:

In the latest nightly, the master volume is way overdriven. On all the songs, this results in having to turn down volume to almost nothing.

### What is the expected behavior?

Normal volume in all the tracks.

### Is there a relevant Pull request?

No

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

_No response_

### If possible provide the steps to reproduce the issue and upload additional media:

open older song
volume is overdriven in the reds
turn down volume to around 3-4 to get decent levels

### PR DESCRIPTION
**Pull request by sapphire-arches**
Fixes #1605

### CODE REVIEW

File: src/deluge/dsp/compressor/rms_feedback.h [hunk 1]
```diff
@@ -34,72 +34,144 @@ class RMSFeedbackCompressor {
...
-	constexpr int32_t getRatioForDisplay() { return ratio; }
+
+	/// Get the current ratio as a full-scale (0 to 2^31) number
+	[[nodiscard]] inline constexpr q31_t getRatio() const { return ratioKnobPos; }
+
+	/// Get the current ratio as an integer
+	///
+	/// @todo Thsi currently rounds (down) to the nearest integer, it would be nice to expose at least a little more of
+	/// the underlying precision.
+	[[nodiscard]] inline constexpr int32_t getRatioForDisplay() const { return ratio; }
```
Comment (m-m-adams) [inline src/deluge/dsp/compressor/rms_feedback.h:119]: This should probably return a float so that we can display 2.x

File: src/deluge/dsp/compressor/rms_feedback.cpp [hunk 2]
```diff
@@ -79,8 +79,8 @@ void RMSFeedbackCompressor::render(StereoSample* buffer, uint16_t numSamples, q3
 		currentVolumeL += amplitudeIncrementL;
 		currentVolumeR += amplitudeIncrementR;
 		// Apply post-fx and post-reverb-send volume
-		thisSample->l = multiply_32x32_rshift32(thisSample->l, currentVolumeL) << 2;
-		thisSample->r = multiply_32x32_rshift32(thisSample->r, currentVolumeR) << 2;
+		thisSample->l = multiply_32x32_rshift32(thisSample->l, currentVolumeL) << 4;
```
[the remark this answers is not in the document]
Comment (m-m-adams) [reply src/deluge/dsp/compressor/rms_feedback.cpp:82]: We can potentially apply 3 compressors to a sound (kit row, kit, song) which can each multiply by 8 for a total possible gain of 2^9 which is a bit dicy

I'm not sure the exact level that samples/waves render at but I think it's 2^20 or something which would definitely clip 

On the other hand it can be fixed by lowering volumes so we could chalk that up to user error

File: src/deluge/dsp/compressor/rms_feedback.cpp [hunk 3]
```diff
@@ -45,7 +45,7 @@ void RMSFeedbackCompressor::renderVolNeutral(StereoSample* buffer, uint16_t numS
 	// this is a bit gross - the compressor can inherently apply volume changes, but in the case of the per clip
 	// compressor that's already been handled by the reverb send, and the logic there is tightly coupled such that
 	// I couldn't extract correct volume levels from it.
-	render(buffer, numSamples, 2 << 26, 2 << 26, finalVolume >> 3);
+	render(buffer, numSamples, ONE_Q31 / 16, ONE_Q31 / 16, finalVolume >> 3);
```
[the remark this answers is not in the document]
Comment (sapphire-arches) [reply src/deluge/dsp/compressor/rms_feedback.cpp:48]: I think this and the change to a right shift by 4 below are cancelling eachother out so the overall gain change is 0db. This gain reduction is a bit of a hack, but without it something clips internally and we get a high pitched whine -- maybe the RMS calculation, because that sums potentially 64 q31s?

File: src/deluge/dsp/compressor/rms_feedback.cpp [hunk 4]
```diff
@@ -110,14 +110,14 @@ float RMSFeedbackCompressor::calcRMS(StereoSample* buffer, uint16_t numSamples)
...
+		q31_t l = thisSample->l - hpfL.doFilter(thisSample->l, hpfMovability_);
+		q31_t r = thisSample->r - hpfL.doFilter(thisSample->r, hpfMovability_);
 		q31_t s = std::max(std::abs(l), std::abs(r));
-		sum += multiply_32x32_rshift32(s, s) << 1;
+		sum += multiply_32x32_rshift32(s, s);
 
 	} while (++thisSample != bufferEnd);
 
-	float ns = float(numSamples);
+	float ns = float(numSamples) / 0.5;
```
Comment (m-m-adams) [inline src/deluge/dsp/compressor/rms_feedback.cpp:120]: nit: this should probably be *2 for clarity and in case the compiler does something dumb

File: src/deluge/dsp/compressor/rms_feedback.h (hunk 1 above)
Comment (sapphire-arches) [reply src/deluge/dsp/compressor/rms_feedback.h:121]: i think this should be done in a separate pr/as future work. the lack of precision in the ratio display has already confused people though, so we definitely should fix it.

**Review by m-m-adams — APPROVED** [review]
