### PR TITLE
Fix #2463 Drumrandomizer ignore mac dot files

### LINKED ISSUE #2463: Drum Randomizer should ignore  Mac .dot files
### Please describe the problem:

Just reorganized all my drum samples to take advantage of the Drum Randomization community feature, which was such a good idea! I renamed all samples in each folder numerically (1.wav, 2.wav, etc).

But, when I hold hit AUDITION + RANDOM, it sometimes loads "._#.wav" (._1.wav, ._57.wav, etc.) which are hidden mac files in that directory, which don't contain any audio, so the drum randomizer has ~50% of actually working.

[BONUS IDEA!] Respect the setting to audition samples that the deluge already has, where you can set to always audition, or audition only if playback stopped, so if playback is stopped... audition the sound when RANDOM is pressed. Thx!

### What is the expected behavior?

AUDITION + RANDOM selects a news sample from the directory the pad's sample is in, ignoring the mac .dot files ("._blah.wav")

### Is there a relevant Pull request?

_No response_

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

Release 1.1/Beethoven

### What is the firmware name:

c1.1.0

### If possible provide the steps to reproduce the issue and upload additional media:

Mac only
1. Initialize a new kit
2. Load a sample from a directory that has other samples in it
3. Hold [AUDITION] + [RANDOM] to randomize the sample
4. Check display to see if an actual sample was loaded, or if a .dot file was loaded erroneously

### PR DESCRIPTION
**Pull request by M0R172**
Fix #2463

isAudioFilename now correctly rejects filenames starting with dot

(isAifffile was not changed because it is used in a different context)

### CODE REVIEW

File: src/deluge/util/functions.cpp [hunk 1]
```diff
@@ -1301,9 +1301,11 @@ void getThingFilename(char const* thingName, int16_t currentSlot, int8_t current
 }
 
 bool isAudioFilename(char const* filename) {
+	if (*filename == '.') {
```
Comment (m-m-adams) [inline src/deluge/util/functions.cpp:1304]: style nit: filename[0] is clearer 
```suggestion
	if (filename[0] == '.') {
```

**Comment by stirman** [comment]
Thank you!

File: src/deluge/util/functions.cpp (hunk 1 above)
Comment (M0R172) [reply src/deluge/util/functions.cpp]: Fully agreed!

**Review by m-m-adams — APPROVED** [review]
