### PR TITLE
Use l10n strings for mod encoder press actions

### LINKED ISSUE #532: Inconsistency in the display name for the stereo chorus effect on 7SEG units
### Please describe the problem:

On a 7SEG unit, when selecting the stereo chorus effect via the TYPE shortcut the display reads "S.CHo". However, when selecting stereo chorus by pressing the gold knob, it reads "StER". 

### What is the expected behavior?

Stereo chorus should be labelled the same in both cases (doesn't matter which, as long as they are consistent)

### Is there a relevant Pull request?

_No response_

### What hardware did you reproduce it with?

7SEG

### What firmware did you reproduce it with?

nightly

### What is the firmware name:

deluge-v1_0_0-nightly+2023_09_09-799dc8b

### If possible provide the steps to reproduce the issue and upload additional media:

_No response_

### PR DESCRIPTION
**Pull request by stellar-aria**
This fixes an oversight where I missed some hard-coded strings in the GlobalEffectable system which were used when the Mod Encoder (gold knobs) were pressed to change FX subtype.

Closes #532.

### CODE REVIEW

File: src/deluge/model/global_effectable/global_effectable.cpp [hunk 1]
```diff
@@ -183,21 +187,21 @@ bool GlobalEffectable::modEncoderButtonAction(uint8_t whichModEncoder, bool on,
...
+					displayText = l10n::getView(STRING_FOR_HPF);
 					break;
 
 				case FilterType::EQ:
-					displayText = "EQ";
+					displayText = l10n::getView(STRING_FOR_EQ);
 					break;
 				}
-				display->displayPopup(displayText);
+				display->displayPopup(displayText.data());
```
Comment (bobtwinkles) [inline src/deluge/model/global_effectable/global_effectable.cpp:204]: maybe out of scope for this change but `Display::displayPopup` should probably take a `string_view` directly.

Comment (stellar-aria) [reply src/deluge/model/global_effectable/global_effectable.cpp:204]: Yeah I was planning on doing that as part of continuing to refactor the displays now that we're post-display unification at some point.

**Comment by stellar-aria** [comment]
Fixed with #553
