### PR TITLE
Fix automation menu view crash

### LINKED ISSUE #3592: Bug with entering automation view editor from menu
### Please describe the problem:

Can't enter automation view editor from menu when automation view was the Root UI prior to entering the menu.

You can enter the automation view editor fine if automation view was not the root UI prior to entering the menu.

### What is the expected behavior?

Pressing song (in arranger) or clip (in clip view) while in a parameter menu should open automation editor.

### When did you start noticing the issue?

Today

### Is there a relevant Pull request?

_No response_

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

_No response_

### If possible provide the steps to reproduce the issue and upload additional media:

_No response_

### PR DESCRIPTION
**Pull request by seangoodvibes**
Fixed crash that would occur when turning select encoder after entering menu from automation view

Also fixed issue where the selected parameter in automation view was not updating when changing the horizontal menu item selection

Fix #3592

### CODE REVIEW

File: src/deluge/gui/menu_item/submenu.cpp [hunk 1]
```diff
@@ -182,8 +182,6 @@ void Submenu::selectEncoderAction(int32_t offset) {
 		} while (offset < 0);
 	}
 	updateDisplay();
-	updatePadLights();
```
Comment (seangoodvibes) [inline src/deluge/gui/menu_item/submenu.cpp:185]: updating pad lights and automation view parameter while scrolling select didn't make any sense so I removed these

updating automation view parameter was definitely causing a crash

File: src/deluge/gui/menu_item/horizontal_menu.cpp [hunk 2]
```diff
@@ -299,7 +299,7 @@ void HorizontalMenu::switchVisiblePage(int32_t direction) {
 
 	renderUIsForOled();
 	updatePadLights();
-	(*current_item_)->updateAutomationViewParameter();
+	// (*current_item_)->updateAutomationViewParameter();
```
Comment (seangoodvibes) [inline src/deluge/gui/menu_item/horizontal_menu.cpp]: commenting all these calls out as I can't figure out why they cause crashes. seems to be because they're trying to update non automatable param menu items

File: src/deluge/gui/ui/sound_editor.cpp [hunk 3]
```diff
@@ -582,7 +582,7 @@ void SoundEditor::handlePotentialParamMenuChange(deluge::hid::Button b, bool on,
 			if (getRootUI() == &automationView) {
 				// if on menu view, swap out root UI to previous UI
 				if (automationView.onMenuView) {
-					previousItem->buttonAction(b, on, inCardRoutine);
+					previousItem->buttonAction(b, true, inCardRoutine);
```
Comment (seangoodvibes) [inline src/deluge/gui/ui/sound_editor.cpp:606]: with the change to select encoder button action, it resulted in !on being passed. for this specific function we always want to pass true so there's no need to forward the actual "on" condition from the button press

File: src/deluge/gui/ui/sound_editor.cpp [hunk 4]
```diff
@@ -959,10 +959,9 @@ void SoundEditor::selectEncoderAction(int8_t offset) {
 	MenuItem* item = getCurrentMenuItem();
 	RootUI* rootUI = getRootUI();
 
-	// Forward to automation view.
-	// - skipped for submenus, since vertical menus don't need it, and horizontal menus need extra case
-	// - TODO: this could be handled by the Automation class via regular forwarding for all cases
-	if (!item->isSubmenu() && rootUI == &automationView && isEditingAutomationViewParam()
+	// Forward to automation view if holding a note
```
Comment (seangoodvibes) [inline src/deluge/gui/ui/sound_editor.cpp:982]: updated this section to only forward to automation view if you're holding a step in automation view, otherwise forward to menu item

also removed extra condition below that I do not believe was necessary

**Comment by seangoodvibes** [comment]
Draft until I incorporate latest feedback from Immers :)
