### PR TITLE
MPE fix - allow note offs on channel 16

### LINKED ISSUE #863: Stuck notes on MPE when Lower is configured to use all 16 channels and Upper is disabled
### Please describe the problem:

I get stuck notes when learning a midi MPE keyboard (Lower) and then playing it, with channels setup to take the whole 16 channels (Upper zone disabled).

### What is the expected behavior?

I don't get stuck notes

### Is there a relevant Pull request?

_No response_

### What hardware did you reproduce it with?

OLED

### What firmware did you reproduce it with?

Nightly

### What is the firmware name:

deluge-v1_0_0-nightly+2023_12_21-58b0d04

### If possible provide the steps to reproduce the issue and upload additional media:

Boot Deluge, connected to an MPE keyboard in the midi input and a midi monitor in the output
Set Upstream device 1 -> MPE -> IN -> Lower num of channels -> 15
Set Upstream device 1 -> MPE -> IN -> Upper num of channels -> 0
Set Upstream device 1 -> MPE -> OUT -> Lower num of channels -> 15
Set Upstream device 1 -> MPE -> OUT -> Upper num of channels -> 0
Create Midi clip and set output channel to MPE Lower
learn the keyboard with Learn + hold audition + press a key
Play any notes in the keyboard
See the midi monitor getting notes but never get the note offs, stuck notes

Repeat but setting MPE IN Lower NumChannels to 14 and MPE OUT Lower NumChannels to 14 and there won't be any stuck notes

### PR DESCRIPTION
**Pull request by m-m-adams**
Fix #863

### CODE REVIEW

File: src/deluge/model/instrument/midi_instrument.cpp [hunk 1]
```diff
@@ -723,7 +723,7 @@ void MIDIInstrument::noteOffPostArp(int32_t noteCodePostArp, int32_t oldOutputMe
 
 	// Or, MPE
 	else {
-		if (oldOutputMemberChannel <= 14) {
```
Comment (soymonitus) [inline src/deluge/model/instrument/midi_instrument.cpp:726]: Have you checked if the change would be needed in lines 52 and 606?

**Review by soymonitus — COMMENTED** [review]
Just one comment I was wondering

File: src/deluge/model/instrument/midi_instrument.cpp (hunk 1 above)
Comment (m-m-adams) [reply src/deluge/model/instrument/midi_instrument.cpp:726]: Yeah, and looks like there's a couple 1s that might need to be zero as well

Thanks for pointing it out!

Comment (soymonitus) [reply src/deluge/model/instrument/midi_instrument.cpp:726]: I tested it and it worked but there was just one small moment where one of the keys of the keyboard didn't trigger sound for a while. Maybe due to these extra changes needed, or maybe not. I will re-test again with your latest changes to see if I encounter any glitch in playing

File: src/deluge/model/instrument/midi_instrument.cpp [hunk 2]
```diff
@@ -602,7 +602,8 @@ void MIDIInstrument::noteOnPostArp(int32_t noteCodePostArp, ArpNote* arpNote) {
 			// Count up notes per member channel. This traversal will *not* find the new note that we're switching on, which will have had its toMIDIChannel set to 16 by Arpeggiator (we'll decide and set it below).
 			for (int32_t n = 0; n < arpeggiator.notes.getNumElements(); n++) {
 				ArpNote* thisArpNote = (ArpNote*)arpeggiator.notes.getElementAddress(n);
-				if (thisArpNote->outputMemberChannel >= 1 && thisArpNote->outputMemberChannel <= 14) {
```
Comment (soymonitus) [inline src/deluge/model/instrument/midi_instrument.cpp:605]: This seems super right, in fact, the calculation of lowestMemberChannel and highestMemberChannel will give you the REAL member channels configured for each zone, to use them in the comparisons in the code (if blocks and whatnot)

File: src/deluge/model/instrument/midi_instrument.cpp [hunk 3]
```diff
@@ -723,39 +724,37 @@ void MIDIInstrument::noteOffPostArp(int32_t noteCodePostArp, int32_t oldOutputMe
 
 	// Or, MPE
 	else {
-		if (oldOutputMemberChannel <= 15) {
```
Comment (soymonitus) [inline src/deluge/model/instrument/midi_instrument.cpp]: Good to completely remove this check since it becomes useless

File: src/deluge/model/instrument/midi_instrument.h [hunk 4]
```diff
@@ -73,7 +73,8 @@ class MIDIInstrument final : public NonAudioInstrument {
 
 	int8_t modKnobCCAssignments[kNumModButtons * kNumPhysicalModKnobs];
 
-	MPEOutputMemberChannel mpeOutputMemberChannels[15]; // Numbers 1 to 14. 0 is bogus
```
Comment (soymonitus) [inline src/deluge/model/instrument/midi_instrument.h:76]: The comment that was there before is bugging me ( // Numbers 1 to 14, 0 is bogus).
Does that mean that the code in .cpp file should be checking always from index 1 of the array and ignoring mpeOutputMemberChannels[0] ? it should ignore it for notes if MPE Lower Zone but should be taken into account if MPE UPPER ZONE. All code in the cpp file is ignoring the last member channel of either zone, first because they set the length of this array to 15 so last channel was always impossible to select, and by adding that comment they are trying to tell us not to use index 0 of the array, which we can see the like in line 52:

```
    for (int32_t c = 1; c <= 14; c++) {
		mpeOutputMemberChannels[c].lastNoteCode = 32767;
		mpeOutputMemberChannels[c].noteOffOrder = 0;
	}
```

Comment (soymonitus) [reply src/deluge/model/instrument/midi_instrument.h:76]: I think we are doing it right now with your modifications because we take into account channel 15 for lower zone, and channel 0 for upper zone.

**Review by soymonitus — APPROVED** [review]
I was seeing some things I was not so sure at the beginning of my review, but after re-checking I edited my comments.
In sum, LGTM

File: src/deluge/model/instrument/midi_instrument.h (hunk 4 above)
Comment (m-m-adams) [reply src/deluge/model/instrument/midi_instrument.h:76]: Ya, it's correct in official only because of a different bug which causes channel 1 and 16 to always be treated as MPE
